# This file stores configurations for your Shopify app.

scopes = "unauthenticated_read_metaobjects, read_checkouts, write_metaobject_definitions, read_metaobjects, write_metaobjects, read_products, unauthenticated_read_content"
