type = "checkout_ui_extension"
name = "Custom data"

extension_points = [
  'Checkout::Dynamic::Render'
]

[capabilities]
network_access = true
block_progress = true
api_access = true

[settings]
  [[settings.fields]]
  key = "title"
  type = "single_line_text_field"
  name = "Banner title"
  description = "Enter a title for the banner."

  [[settings.fields]]
  key = "description"
  type = "single_line_text_field"
  name = "Banner description"
  description = "Enter a description for the banner."

  [[settings.fields]]
  key = "image"
  type = "single_line_text_field"
  name = "Banner image"
  description = "https://cdn.shopify.com/s/files/1/0723/3640/8867/files/elementor-placeholder-image.webp?v=1676858525"

  [[settings.fields]]
  key = "tooltip"
  type = "single_line_text_field"
  name = "Banner tooltip"
  description = "Enter a title for tooltip"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
# [settings]

